version: "3"
services:
  db:
    image: "postgres"
    container_name: "pt_db"
    environment:
      - POSTGRES_USER=pt
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_DB=pt
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data