spring:
  jpa:
    hibernate:
      ddl-auto: none
  database:
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/pt
    username: pt
    password: s3cr3t
  flyway:
    enabled: true
    table: schema_version
wicket:
  external:
    spring:
      security:
        enabled: true

---

spring:
  profiles: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}